# Generated by Django 5.0 on 2024-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
    ]
