# Generated by Django 5.0 on 2024-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_is_urgent"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="is_urgent",),
    ]
